name: Tests 🎳

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
#  tags:
#    - '^\d+\.\d+\.\d+$'

jobs:
  test-flake8:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
          architecture: x64
      - name: Checkout
        uses: actions/checkout@master
      - name: Install flake8
        run: pip install flake8
      - name: Run flake8
        uses: suo/flake8-github-action@releases/v1
        with:
          checkName: 'test-flake8'   # NOTE: this needs to be the same as the job name
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

  test-qgis:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .docker
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Launching docker-compose
        run: ./start.sh with-qgis
      - name: Running tests
        run: ./exec.sh

  test-migration:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .docker
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Launching docker-compose
        run: ./start.sh
      - name: Running tests
        run: ./install_migrate_generate.sh

  release:
    runs-on: ubuntu-latest
    needs: [test-flake8, test-qgis, test-migration]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install qgis-plugin-ci
        run: pip3 install git+https://github.com/Gustry/qgis-plugin-ci.git
      - name: Changelog
        run: qgis-plugin-ci changelog ${{ github.ref }} > ../release.md
      - name: Create Release
        uses: jbolda/create-release@v1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body_path: ../release.md
          draft: false
          prerelease: false
      - name: Deploy plugin
        run: qgis-plugin-ci release ${{ github.ref }} --github-token ${secrets.GH_TOKEN} --create-plugin-repo --allow-uncommitted-changes

      - name: Update code-source
        run: .github/push_to_github.sh
