name: Tests migrations
on: [push, pull_request]

defaults:
  run:
    working-directory: .docker

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Launching docker-compose
        run: ./start.sh

      - name: Running tests
        run: ./install_migrate_generate.sh
